monero-project/monero-docs

mkdocs.yml
overrides/partials/copyright.html

overrides: copyright partial with i18n

---

README.md

preview: https://github.com/nahuhh/monero-docs/blob/README/README.md

readme: fix link

---

mkdocs.yml

```
static_templates:
- 404.html
```
Moved to fix a build error

mkdocs.yml: white header, orange accent

---

docs/en/index.md
mkdocs.yml

discussion on which irc link to use (irc:// or web.libera etc)
https://34.md.monerodevs.org

index.md: add buttons

---

mkdocs.yml

https://31.md.monerodevs.org
notes: 
1. ~~squash~~
2. ~~moved some commits to new prs~~
2. ~~unused menus (mining) to be commented until files are created~~
3. organize folder structure in new pr

mkdocs.yml: simplify menus

---

docs/macros/monerod.yml
main.py
mkdocs.yml
requirements.txt

plugins: add macros

---

Dockerfile_coolify

Dockerfile_coolify: pin docker python version

---

docs/en/technical-specs.md

https://65.md.monerodevs.org/technical-specs/#current-blockchain-size

tokenomics: macros for blockchain sizes

---

docs/overrides.css
mkdocs.yml

theme: fix nojs & override defaults

---

docs/en/rpc-library/monerod-rpc.md

https://github.com/monero-project/monero-site/pull/2263
https://github.com/monero-project/monero-site/pull/2265
https://github.com/monero-project/monero-site/pull/2266
https://github.com/monero-project/monero-site/pull/2320

daemon-rpc: migrate prs from -site

---

docs/en/rpc-library/wallet-rpc.md

https://github.com/monero-project/monero-site/pull/2249
https://github.com/monero-project/monero-site/pull/2250
https://github.com/monero-project/monero-site/pull/2306

wallet-rpc: migrate prs from -site

---

docs/macros/includes/tor_template

https://82.md.monerodevs.org/running-node/monerod-tori2p

tor: add missing port

---

mkdocs.yml

mkdocs.yml: nav fix

---

.gitignore
docs/en/cryptography/asymmetric/introduction.md
docs/en/mnemonics/index.md
docs/en/mnemonics/legacy.md
docs/en/mnemonics/mymonero.md
docs/en/mnemonics/polyseed.md
mkdocs.yml

in one commit, without fucking up the commit history

add mnemonics section

---

.github/workflows/comment_pr.yml

we're short staffed over the holidays so every little helps

ci: comment coolify url on each PR

---

docs/en/infrastructure/networks.md

infra: networks; remove rino

---

docs/en/public-address/index.md
docs/en/public-address/standard-address.md

- remove deprecated notice for integrated address
- add stagenet prefix
Requires #106

addresses: rm integrated addr deprecated notice, add stagenet prefix

---

docs/en/rpc-library/wallet-rpc.md

wallet-rpc: add get_default_fee_priority

---

docs/en/infrastructure/networks.md

networks: add clearnet xmrchain stagenet + testnet explorers

---

docs/en/cryptography/asymmetric/edwards25519.md
docs/en/infrastructure/monero-pulse.md
docs/en/mnemonics/polyseed.md
docs/en/public-address/subaddress.md
docs/en/running-node/monerod-systemd.md

use netcat(nc) instead of nmap (squashed)

---

docs/en/interacting/monero-wallet-rpc-reference.md
docs/en/interacting/monerod-reference.md
docs/en/rpc-library/monerod-rpc.md
docs/en/rpc-library/wallet-rpc.md
docs/overrides.css

https://147.md.monerodevs.org
builds on top of #141

interacting: add/fix/organize defaults for wallet-rpc and monerod

---

docs/en/infrastructure/networks.md

I've created a testnet and stagenet faucet for Monero to help developers.
Testnet: https://cypherfaucet.com/xmr-testnet
Stagenet: https://cypherfaucet.com/xmr-stagenet

networks: add new stagenet and testnet faucet

---

docs/en/interacting/overview.md
docs/en/interacting/verify-monero-binaries.md

versions: use macro on verifying and overview

---

docs/en/cold-storage/offline-transaction-signing.md
docs/en/infrastructure/networks.md
docs/en/public-address/standard-address.md
docs/en/rpc-library/wallet-rpc.md

fix some minor issues in comments

chore: fix some minor issues in comments
